---
# tasks file for install_tools
- name: "Install Neovim build prerequisites"
  community.general.xbps:
    name:
      - base-devel
      - cmake
      - curl
      - git
    state: present
  become: true
  become_method: sudo

- name: "Clone Neovim source"
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim'
    dest: /opt/neovim
    version: stable
  become: true
  become_method: sudo

- name: "Build Neovim from source"
  ansible.builtin.shell: |
   cd /opt/neovim && \
   make CMAKE_BUILD_TYPE=Release && \
   make install
  args:
    creates: /usr/bin/nvim
  become: true
  become_method: sudo

- name: "Set default git editor to Neovim"
  community.general.git_config:
    name: core.editor
    value: nvim
    scope: global
    state: present

# move to different role - setup_environment
- name: "Create tarballs directory for software installs"
  ansible.builtin.shell: |
    mkdir /opt/tarballs
  args:
    creates: /opt/tarballs
  become: true
  become_method: sudo

- name: "Download golang 1.20.5 amd64 tarball"
  ansible.builtin.uri:
    url: 'https://go.dev/dl/go1.20.5.linux-amd64.tar.gz'
    dest: /opt/tarballs/
    creates: /opt/tarballs/go1.20.5.linux-amd64.tar.gz
  become: true
  become_method: sudo

- name: "Extract golang archive to /usr/local"
  ansible.builtin.shell: |
    tar -C /usr/local -xzf /opt/tarballs/go1.20.5.linux-amd64.tar.gz
  args:
    creates: /usr/local/go
  become: true
  become_method: sudo
