---
# tasks file for install_tools
- name: "Install Neovim build prerequisites"
  community.general.xbps:
    name:
      - base-devel
      - cmake
      - curl
      - git
    state: present
  become: true
  become_method: sudo

- name: "Clone Neovim source"
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim'
    dest: /opt/neovim
    version: stable
  become: true
  become_method: sudo

- name: "Build Neovim from source"
  ansible.builtin.shell: |
   cd /opt/neovim && \
   make CMAKE_BUILD_TYPE=Release && \
   make install
  args:
    creates: /usr/bin/nvim
  become: true
  become_method: sudo

- name: "Set default git editor to Neovim"
  community.general.git_config:
    name: core.editor
    value: nvim
    scope: global
    state: present
